
# This is a basic workflow to help you get started with Actions

name: CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  package:
      defaults:
        run:
          working-directory: ./
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      needs: [analyze]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2.3.1
        - run: docker login --username ${DOCKER_LOGIN} --password ${DOCKER_TOKEN}
        - run: docker image build -t game-manager-svc .
        - run: docker image tag game-manager-svc rpsultimate/game-manager-svc
        - run: docker image push rpsultimate/game-manager-svc
        - run: docker logout